# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package.json package-lock.json ./

# Install dependencies while ignoring any scripts to speed up Docker build if needed
RUN npm install --ignore-scripts

# Copy source code
COPY . .

# Build the project
RUN npm run build

# Expose any ports if needed (none for stdio based MCP)

# Set the entrypoint
CMD [ "node", "build/index.js" ]
